# Change these first
owner: autoactions # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Sink
    url: https://122399.xyz/
  - name: Openai API
    url: https://openai.aigateway.lirtual.cloudns.org/
    icon: https://openai.com/favicon.ico
  - name: RSSHub
    url: https://rsshub.lirtual.cloudns.org/
  - name: Telegraph Image
    url: https://img.lirtual.cloudns.org/
  - name: FlareDrive
    url: https://flaredrive.lirtual.cloudns.org/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.lirtual.cloudns.org
  # baseUrl: /upptime
  logoUrl: https://uptime.lirtual.cloudns.org/upptime-icon.svg
  name: Uptime
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  # navbar:
  #   - title: Status
  #     href: /
  #   - title: GitHub
  #     href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
